// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_CkPgfmRaZKsBhz5QaKaqk5MK42itXoA',
    appId: '1:155781723609:web:e87f633f89f14bdffc55c8',
    messagingSenderId: '155781723609',
    projectId: 'myportfolio2-c2742',
    authDomain: 'myportfolio2-c2742.firebaseapp.com',
    databaseURL: 'https://myportfolio2-c2742.firebaseio.com',
    storageBucket: 'myportfolio2-c2742.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGtKmSCqQNzPAXJCrr-q-05hR3N3S2jNI',
    appId: '1:155781723609:android:6e3ce42635eef7e2fc55c8',
    messagingSenderId: '155781723609',
    projectId: 'myportfolio2-c2742',
    databaseURL: 'https://myportfolio2-c2742.firebaseio.com',
    storageBucket: 'myportfolio2-c2742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWb2yRt5pjLHYnW1tGf81Hh_eT3Ti31zI',
    appId: '1:155781723609:ios:197957d452178b99fc55c8',
    messagingSenderId: '155781723609',
    projectId: 'myportfolio2-c2742',
    databaseURL: 'https://myportfolio2-c2742.firebaseio.com',
    storageBucket: 'myportfolio2-c2742.appspot.com',
    iosBundleId: 'com.example.todoAppFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWb2yRt5pjLHYnW1tGf81Hh_eT3Ti31zI',
    appId: '1:155781723609:ios:197957d452178b99fc55c8',
    messagingSenderId: '155781723609',
    projectId: 'myportfolio2-c2742',
    databaseURL: 'https://myportfolio2-c2742.firebaseio.com',
    storageBucket: 'myportfolio2-c2742.appspot.com',
    iosBundleId: 'com.example.todoAppFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_CkPgfmRaZKsBhz5QaKaqk5MK42itXoA',
    appId: '1:155781723609:web:87c3dbf7344e283ffc55c8',
    messagingSenderId: '155781723609',
    projectId: 'myportfolio2-c2742',
    authDomain: 'myportfolio2-c2742.firebaseapp.com',
    databaseURL: 'https://myportfolio2-c2742.firebaseio.com',
    storageBucket: 'myportfolio2-c2742.appspot.com',
  );

}