// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'main.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'main.g.dart';

// // immutable
// @freezed
// class Person with _$Person { // "_$"を接頭辞として使用
//   const factory Person({ // コンストラクタを定義するときは"factory"を記述("const"はお好きにどうぞ)
//     required String firstName,
//     required String lastName,
//     required int age,
//   }) = _Person;

//   // fromJsonを定義したことで、デシリアル化（不連続化）が可能
//   factory Person.fromJson(Map<String, Object?> json) => _$PersonFromJson(json);
// }

// // age以外は変更可能
// @unfreezed
// class Person with _$Person {
//   factory Person({
//     required String firstName,
//     required String lastName,
//     required final int age,
//   }) = _Person;

//   factory Person.fromJson(Map<String, Object?> json)
//       => _$PersonFromJson(json);
// }

// copyWithの使い方
@freezed
class Person with _$Person {
  factory Person(String name, int? age) = _Person;
}

void main() {
  var person = Person('Remi', 24);

  // `age` not passed, its value is preserved
  print(person.copyWith(name: 'Dash')); // Person(name: Dash, age: 24)
  // `age` is set to `null`
  print(person.copyWith(age: null)); // Person(name: Remi, age: null)
}
